trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet restore
  displayName: 'install build dependencies'

- script: |
    dotnet test -s nunit.runsettings
  displayName: 'Run tests'
- bash: |
    find . -type f 
  displayName: '(debug) list files in working directory'
- bash: |
    res=$(curl -o - -H "Content-Type: multipart/form-data" -u $(jira_user):$(jira_password) -F "file=@./bin/Debug/net5.0/TestResults/nunit_webdriver_tests.xml" "$(jira_server_url)/rest/raven/2.0/import/execution/nunit?projectKey=$(project_key)")
    echo "$res"
  displayName: 'Import results to Xray'
