trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet restore
  displayName: 'install build dependencies'

- script: |
    dotnet test -s nunit.runsettings
  displayName: 'Run tests'

- bash: |
    curl -H "Content-Type: multipart/form-data" -u $(jira_user):$(jira_password) -F "file=@TestResults/nunit_webdriver_tests.xml" "$(jira_server_url)/rest/raven/2.0/import/execution/nunit?projectKey=$(project_key)"
